feat: hide information about spot that is too lengthy
bopjesvla/hitch pull request #59
Opened 2024-06-07 21:56 UTC by tillwenke

2024-06-08 12:06 UTC, bopjesvla commented
This looks very good!

Do you know how the details element remembers its open/closed state? Should we add it to LocalStorage just to be sure?

Although we don't store it, most browsers remember the <select> value for the hitchhiking signal. I've seen people bulk-adding reviews where they change the signal for every review. People might forget to do this once they've collapsed the details element. Possible solutions:

- Blank out the select element on reload. Not my favorite choice.
- Always expand the details element if the select value is already set, to show the user. Seems good now, might get annoying if we add a lot of questions.
- Move the signal out of the details element, leaving only gender info. Also not my favorite choice.
- No details element, break the form in two parts, with a button "Submit summary review" after the first part and a button "Submit extended review" after the extended questions. Might be confusing because web forms are rarely structured this way.

2024-06-08 17:30 UTC, tillwenke commented
didnt find anything about that the open state was remembered. also tested on some sites where it got back to its initial state when reloading the site.

I chose 2. bc it encourages to add the extra info and prevents the user from forgetting that some values were set already.

could open an issue to never remember the signal state.

2024-06-08 19:11 UTC, bopjesvla commented
I could have sworn the element remembered to stay closed when I tested it earlier today. I don't think leaving it open at all times makes sense. If it's always open when the form is shown, users may as well scroll past it instead of collapsing it.

How about this:

- The extended form is open by default
- It remembers when it's closed
- If the form is submitted and the extended form has never been shown but it has previously entered data, the form asks for confirmation

2024-06-08 19:13 UTC, bopjesvla commented
> could open an issue to never remember the signal state.

More often than not, this remains the same though

2024-06-08 19:41 UTC, bopjesvla commented
I've been thinking about this and I'm kinda worried about making reviews feel like a questionnaire. Rereading #37, that's the reason I originally suggested this feature, and why I originally suggested it'd be collapsed by default.

I'm leaning that way again.

2024-09-13 14:37 UTC, tillwenke commented
how do we go about new column in the db? could you add "datetime_ride" to it?

2024-09-14 18:27 UTC, tillwenke commented
Ready to merge.
Decided to just force to look at the collapsed items before submitting if values are set there.

Checking if it was open at some point was too complex.

2024-09-25 18:26 UTC, bopjesvla requested changes

2024-09-25 18:26 UTC, bopjesvla commented on src.html
> +        <script>
Let's keep all JS in map.js for now. I know it's not ideal, but we'll get to this when we move to Vue or something.

2024-09-25 18:27 UTC, bopjesvla commented
I updated the styling to make the main flow more apparent.

2024-09-25 18:28 UTC, bopjesvla requested changes

2024-09-25 18:28 UTC, bopjesvla commented on src.html
> +                <summary id="ds" style="display:list-item">more optional fields</summary>
more descriptive ID

2024-09-25 20:38 UTC, tillwenke commented
thanks for the review. can we merge now?
@bopjesvla do we have the datetime_ride column in the database?

2024-10-04 17:09 UTC, bopjesvla commented
I don't think you correctly merged the master branch; the new sidebar is gone for example.

2024-10-06 14:46 UTC, tillwenke commented
Done :)

2024-10-11 14:09 UTC, bopjesvla commented
I've added the column in the db. Two more things:

"When did you get the ride?"

Reviewers don't always get a ride, and you might still want the time of day they hitchhiked. I can't really think of one natural way to ask this, so I'd go with the current option if they logged a destination (i.e. points[1].lat is a number) and add something like "If you didn't get a ride, when did you stop soliciting rides?" if not.

I'd recommend using classList.toggle on the spot form and hiding the addition using CSS

2024-10-11 14:16 UTC, bopjesvla commented
You can also replace the datetime with the ride_datetime if it exists, and add an icon to show it's not the time of review. Something like 🕒 November, 2006 instead of --November, 2024.

2024-10-11 15:31 UTC, bopjesvla commented
download function in a separate pr please

and you can just make a .sh with the download line in the README

2024-10-11 15:35 UTC, bopjesvla commented
There's a change to the dashboard as well. Again, remember to check the diffs before committing.

2024-10-11 16:33 UTC, tillwenke commented
looks good now imo

2024-10-12 10:39 UTC, bopjesvla requested changes

2024-10-12 10:39 UTC, bopjesvla commented on show.py
> +    + points.apply(get_displayed_time, axis=1)
```
submitted = points.datetime.dt.strftime(...)
points.ride_datetime.dt.strftime(...).fillna(submitted)
```

2024-10-12 10:39 UTC, bopjesvla commented on show.py
> +    + points[oldies].apply(get_displayed_time, axis=1)
oldies don't have a ride time

2024-10-12 10:39 UTC, bopjesvla commented on map.js
> +            function destinationSet(){
this function always returns the same thing, you can just make it a variable

2024-10-12 10:39 UTC, bopjesvla commented on map.js
> +                document.getElementById("no-ride").classList.toggle("make-invisible");
look at the docs of toggle, you'll want to use the two-argument variant taking a boolean

2024-10-12 10:42 UTC, bopjesvla commented on src.html
> +                <label for="datetime_ride">When did you get the ride?<p id="no-ride">If you didn't get a ride, when did you stop soliciting rides?</p></label>
not sure you can put a paragraph in a label, unless it looks goofy just use a span

2024-10-12 19:32 UTC, tillwenke commented on map.js
> +            function destinationSet(){
good catch

2024-10-12 19:58 UTC, tillwenke commented on map.js
> +                document.getElementById("no-ride").classList.toggle("make-invisible");
which behavior do you want to achieve by setting the force param? https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle

2024-10-12 19:58 UTC, tillwenke commented
done

2024-10-12 20:01 UTC, tillwenke commented
@bopjesvla how do we know people didnt get a ride? wanna open another issue for this?

2024-10-21 15:10 UTC, bopjesvla commented on map.js
> +                document.getElementById("no-ride").classList.toggle("make-invisible");
You don't want to inverse the value, you want to set it to the value of destinationSet (#no-ride is never removed from the dom, so toggling it can also remove the class)

2024-10-21 16:41 UTC, tillwenke commented on map.js
> +                document.getElementById("no-ride").classList.toggle("make-invisible");
like this?

2024-10-24 18:28 UTC, bopjesvla commented
> @bopjesvla how do we know people didnt get a ride? wanna open another issue for this?

There used to be an option for people who didn't get a ride, but it was misused to skip (even though there was also a skip option). Bad rating + a skip is probably the best way to tell

2024-10-24 18:40 UTC, bopjesvla requested changes
I missed a few little things

2024-10-24 18:40 UTC, bopjesvla commented on map.js
> +const form = document.querySelector("form");
#spot-form is probably better here

2024-10-24 18:40 UTC, bopjesvla commented on map.js
> +const form = document.querySelector("form");
also we have the $$ helper to keep the code clean, probably use it everywhere instead of querySelector and getElementById

2024-10-24 18:40 UTC, bopjesvla commented on map.js
> +        details.open = true;
Besides this, keep track of whether this warning has already shown

you dont want people to check, close the summary again, then submit, only to get the same error again

2024-11-07 10:57 UTC, merged