another report option to collect links between hitchwiki spot descritions and the corresponding hitchmap spot
bopjesvla/hitch pull request #75
Opened 2024-08-16 06:41 UTC by tillwenke

2024-08-17 00:56 UTC, tillwenke commented
odd behavior, could not figure out why: after viewing a spot that has a hitchwiki link, this link displays as well for all other spots even if they do not have a hitchwiki link. @bopjesvla do you have an idea why this happens?

2024-09-04 17:29 UTC, bderui commented
Commented on issue

2024-09-21 19:30 UTC, bopjesvla commented
I don't know, but ideally we'd do the linking automatically. Many Hitchwiki articles have lat lon information we can parse. The database is freely available.

2024-09-25 12:42 UTC, bopjesvla commented
Amsterdam has coordinates: `<map lat='52.38278242102423' lng='4.90844612121582' zoom='11' view='3'/> `

Ideally, we'd provide this map.

2024-09-25 12:44 UTC, bopjesvla commented
And the other way around: download the Hitchwiki db dump and extract all of the coordinates. Then, for every spot near one of those coordinates, link the page.

2024-09-25 18:02 UTC, tillwenke commented
This does not reflect what I am trying to achieve.

There are specific spots that are described in the hitchwiki. usually for a city there are main directions. each direction can have various options. like https://hitchwiki.org/en/Dresden#Option_1 - this mentions 2 particular spots that (in this case) are kindly liked to hitchmap spots.
So there is a whole high quality detailed description of those spots on hitchwiki that we currently do not make available to hitchmap users.
this pr is a first step towards leveraging this information and connecting map and wiki.

2024-10-04 19:17 UTC, bopjesvla requested changes

2024-10-04 19:17 UTC, bopjesvla commented on modify_db.ipynb
are you sure this is necessary? doesn't the pandas to_sql create the table if it doesn't exist?

2024-10-06 14:36 UTC, merged